### ISSUE TITLE
Accuracy?

### ISSUE THREAD

**Issue by Kentoseth** [NotThorz/ReciteQuran#1]
Assalamu alaikum

How accurate is this tool? I've been reading a bit and it seems that `pocketsphinx` is considered far from the advanced ASR tools (but maybe it's accurate here).

**Comment by NotThorz** [comment]
You are correct , the tool is just a prototype of how I want to do things , I'm working on a more advanced Django Web App that uses ML to check users pronunciation and TAJWEED rules , since there isn't really an accurate Arabic to text speech recognition library ,I'm creating one , but work is delaying the project  , have a nice day
